### ISSUE TITLE
Can't build on Ubuntu 14.04 TLS

### ISSUE THREAD

**Issue by corentingurtner** [xdissent/node-pcm-utils#3]
I can't build on Ubuntu 14.04 TLS with node 0.11.14

```
> pcm-utils@0.0.2 install /tmp/node_modules/pcm-utils
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/tmp/node_modules/pcm-utils/build'
CXX(target) Release/obj.target/binding/binding.o
In file included from ../binding.cc:2:0:
../mixer.h:17:33: error: expected class-name before ‘{’ token
class Mixer : public ObjectWrap {
^
../mixer.h:39:5: error: ‘uv_work_t’ does not name a type
uv_work_t request;
^
../mixer.h:77:34: error: ‘Arguments’ does not name a type
static Handle<Value> New(const Arguments& args);
 ^
../mixer.h:77:45: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   static Handle<Value> New(const Arguments& args);
                                             ^
../mixer.h:78:36: error: ‘Arguments’ does not name a type
   static Handle<Value> Write(const Arguments& args);
                                    ^
../mixer.h:78:47: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   static Handle<Value> Write(const Arguments& args);
                                               ^
../mixer.h:79:70: error: ‘AccessorInfo’ does not name a type
   static Handle<Value> ChannelBuffersGetter(Local<String> str, const AccessorInfo& accessor);
                                                                      ^
../mixer.h:79:84: error: ISO C++ forbids declaration of ‘accessor’ with no type [-fpermissive]
   static Handle<Value> ChannelBuffersGetter(Local<String> str, const AccessorInfo& accessor);
                                                                                    ^
../mixer.h:80:69: error: ‘AccessorInfo’ does not name a type
   static Handle<Value> ChannelsReadyGetter(Local<String> str, const AccessorInfo& accessor);
                                                                     ^
../mixer.h:80:83: error: ISO C++ forbids declaration of ‘accessor’ with no type [-fpermissive]
   static Handle<Value> ChannelsReadyGetter(Local<String> str, const AccessorInfo& accessor);
                                                                                   ^
../mixer.h:81:72: error: ‘AccessorInfo’ does not name a type
   static Handle<Value> SamplesPerBufferGetter(Local<String> str, const AccessorInfo& accessor);
                                                                        ^
../mixer.h:81:86: error: ISO C++ forbids declaration of ‘accessor’ with no type [-fpermissive]
   static Handle<Value> SamplesPerBufferGetter(Local<String> str, const AccessorInfo& accessor);
                                                                                      ^
../mixer.h:82:62: error: ‘AccessorInfo’ does not name a type
   static Handle<Value> MixingGetter(Local<String> str, const AccessorInfo& accessor);
                                                              ^
../mixer.h:82:76: error: ISO C++ forbids declaration of ‘accessor’ with no type [-fpermissive]
   static Handle<Value> MixingGetter(Local<String> str, const AccessorInfo& accessor);
                                                                            ^
../mixer.h:85:23: error: ‘uv_work_t’ has not been declared
   static void DoWrite(uv_work_t* req);
                       ^
../mixer.h:86:26: error: ‘uv_work_t’ has not been declared
   static void AfterWrite(uv_work_t* req);
                          ^
../mixer.h:89:21: error: ‘uv_work_t’ has not been declared
   static void DoMix(uv_work_t* req);
                     ^
../mixer.h:90:24: error: ‘uv_work_t’ has not been declared
   static void AfterMix(uv_work_t* req);
                        ^
../mixer.h: In constructor ‘pcmutils::Mixer::Mixer()’:
../mixer.h:22:13: error: class ‘pcmutils::Mixer’ does not have any field named ‘ObjectWrap’
   Mixer() : ObjectWrap(), channels(0), alignment(0), format(0), mixing(false) {
             ^
../mixer.h:23:20: error: ‘class v8::Persistent<v8::Array>’ has no member named ‘Clear’
     channelBuffers.Clear();
                    ^
../mixer.h:24:19: error: ‘class v8::Persistent<v8::Array>’ has no member named ‘Clear’
     channelsReady.Clear();
                   ^
../mixer.h:25:14: error: ‘class v8::Persistent<v8::Function>’ has no member named ‘Clear’
     callback.Clear();
              ^
../mixer.h: In destructor ‘pcmutils::Mixer::~Mixer()’:
../mixer.h:33:20: error: ‘class v8::Persistent<v8::Array>’ has no member named ‘Dispose’
     channelBuffers.Dispose();
                    ^
../mixer.h:34:19: error: ‘class v8::Persistent<v8::Array>’ has no member named ‘Dispose’
     channelsReady.Dispose();
                   ^
../mixer.h:35:14: error: ‘class v8::Persistent<v8::Function>’ has no member named ‘Dispose’
     callback.Dispose();
              ^
../mixer.h: In constructor ‘pcmutils::Mixer::Baton::Baton(pcmutils::Mixer*)’:
../mixer.h:43:12: error: ‘class pcmutils::Mixer’ has no member named ‘Ref’
       mix->Ref();
            ^
../mixer.h:44:7: error: ‘request’ was not declared in this scope
       request.data = this;
       ^
../mixer.h: In destructor ‘virtual pcmutils::Mixer::Baton::~Baton()’:
../mixer.h:47:12: error: ‘class pcmutils::Mixer’ has no member named ‘Unref’
       mix->Unref();
            ^
../mixer.h: In constructor ‘pcmutils::Mixer::WriteBaton::WriteBaton(pcmutils::Mixer*, v8::Handle<v8::Function>, int)’:
../mixer.h:56:47: error: no matching function for call to ‘v8::Persistent<v8::Function>::New(v8::Handle<v8::Function>&)’
       callback = Persistent<Function>::New(cb_);
                                               ^
../mixer.h:56:47: note: candidate is:
In file included from /root/.node-gyp/0.11.14/src/node.h:61:0,
                 from ../binding.cc:1:
/root/.node-gyp/0.11.14/deps/v8/include/v8.h:5724:4: note: static T* v8::PersistentBase<T>::New(v8::Isolate*, T*) [with T = v8::Function]
 T* PersistentBase<T>::New(Isolate* isolate, T* that) {
    ^
/root/.node-gyp/0.11.14/deps/v8/include/v8.h:5724:4: note:   candidate expects 2 arguments, 1 provided
In file included from ../binding.cc:2:0:
../mixer.h: In destructor ‘virtual pcmutils::Mixer::WriteBaton::~WriteBaton()’:
../mixer.h:59:16: error: ‘class v8::Persistent<v8::Function>’ has no member named ‘Dispose’
       callback.Dispose();
                ^
../mixer.h: In constructor ‘pcmutils::Mixer::MixBaton::MixBaton(pcmutils::Mixer*)’:
../mixer.h:67:65: error: ‘malloc’ was not declared in this scope
       channelData = (char**)malloc(mix->channels * sizeof(char*));
                                                                 ^
../mixer.h:69:58: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::Array>’
         channelData[i] = Buffer::Data(mix->channelBuffers->Get(i)->ToObject());
                                                          ^
../mixer.h: In destructor ‘virtual pcmutils::Mixer::MixBaton::~MixBaton()’:
../mixer.h:73:23: error: ‘free’ was not declared in this scope
       free(channelData);
                       ^
In file included from ../binding.cc:3:0:
../unzipper.h: At global scope:
../unzipper.h:17:36: error: expected class-name before ‘{’ token
 class Unzipper : public ObjectWrap {
                                    ^
../unzipper.h:35:5: error: ‘uv_work_t’ does not name a type
     uv_work_t request;
     ^
../unzipper.h:83:34: error: ‘Arguments’ does not name a type
   static Handle<Value> New(const Arguments& args);
                                  ^
../unzipper.h:83:45: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   static Handle<Value> New(const Arguments& args);
                                             ^
../unzipper.h:84:36: error: ‘Arguments’ does not name a type
   static Handle<Value> Unzip(const Arguments& args);
                                    ^
../unzipper.h:84:47: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   static Handle<Value> Unzip(const Arguments& args);
                                               ^
../unzipper.h:87:23: error: ‘uv_work_t’ has not been declared
   static void DoUnzip(uv_work_t* req);
                       ^
../unzipper.h:88:26: error: ‘uv_work_t’ has not been declared
   static void AfterUnzip(uv_work_t* req);
                          ^
../unzipper.h: In constructor ‘pcmutils::Unzipper::Unzipper()’:
../unzipper.h:22:16: error: class ‘pcmutils::Unzipper’ does not have any field named ‘ObjectWrap’
   Unzipper() : ObjectWrap(), channels(0), alignment(0), frameAlignment(0), unzipping(false) {
                ^
../unzipper.h:23:20: error: ‘class v8::Persistent<v8::Array>’ has no member named ‘Clear’
     channelBuffers.Clear();
                    ^
../unzipper.h: In destructor ‘pcmutils::Unzipper::~Unzipper()’:
../unzipper.h:31:20: error: ‘class v8::Persistent<v8::Array>’ has no member named ‘Dispose’
     channelBuffers.Dispose();
                    ^
../unzipper.h: In constructor ‘pcmutils::Unzipper::Baton::Baton(pcmutils::Unzipper*)’:
../unzipper.h:39:12: error: ‘class pcmutils::Unzipper’ has no member named ‘Ref’
       unz->Ref();
            ^
../unzipper.h:40:7: error: ‘request’ was not declared in this scope
       request.data = this;
       ^
../unzipper.h: In destructor ‘virtual pcmutils::Unzipper::Baton::~Baton()’:
../unzipper.h:43:12: error: ‘class pcmutils::Unzipper’ has no member named ‘Unref’
       unz->Unref();
            ^
../unzipper.h: In constructor ‘pcmutils::Unzipper::UnzipBaton::UnzipBaton(pcmutils::Unzipper*, v8::Handle<v8::Function>, v8::Handle<v8::Object>)’:
../unzipper.h:59:47: error: no matching function for call to ‘v8::Persistent<v8::Function>::New(v8::Handle<v8::Function>&)’
       callback = Persistent<Function>::New(cb_);
                                               ^
../unzipper.h:59:47: note: candidate is:
In file included from /root/.node-gyp/0.11.14/src/node.h:61:0,
                 from ../binding.cc:1:
/root/.node-gyp/0.11.14/deps/v8/include/v8.h:5724:4: note: static T* v8::PersistentBase<T>::New(v8::Isolate*, T*) [with T = v8::Function]
 T* PersistentBase<T>::New(Isolate* isolate, T* that) {
    ^
/root/.node-gyp/0.11.14/deps/v8/include/v8.h:5724:4: note:   candidate expects 2 arguments, 1 provided
In file included from ../binding.cc:3:0:
../unzipper.h:61:45: error: no matching function for call to ‘v8::Persistent<v8::Object>::New(v8::Handle<v8::Object>&)’
       chunk = Persistent<Object>::New(chunk_);
                                             ^
../unzipper.h:61:45: note: candidate is:
In file included from /root/.node-gyp/0.11.14/src/node.h:61:0,
                 from ../binding.cc:1:
/root/.node-gyp/0.11.14/deps/v8/include/v8.h:5724:4: note: static T* v8::PersistentBase<T>::New(v8::Isolate*, T*) [with T = v8::Object]
 T* PersistentBase<T>::New(Isolate* isolate, T* that) {
    ^
/root/.node-gyp/0.11.14/deps/v8/include/v8.h:5724:4: note:   candidate expects 2 arguments, 1 provided
In file included from ../binding.cc:3:0:
../unzipper.h:62:37: error: no matching function for call to ‘Data(v8::Persistent<v8::Object>&)’
       chunkData = Buffer::Data(chunk);
                                     ^
../unzipper.h:62:37: note: candidates are:
In file included from ../mixer.h:5:0,
                 from ../binding.cc:2:
/root/.node-gyp/0.11.14/src/node_buffer.h:40:19: note: char* node::Buffer::Data(v8::Handle<v8::Value>)
 NODE_EXTERN char* Data(v8::Handle<v8::Value> val);
                   ^
/root/.node-gyp/0.11.14/src/node_buffer.h:40:19: note:   no known conversion for argument 1 from ‘v8::Persistent<v8::Object>’ to ‘v8::Handle<v8::Value>’
/root/.node-gyp/0.11.14/src/node_buffer.h:41:19: note: char* node::Buffer::Data(v8::Handle<v8::Object>)
 NODE_EXTERN char* Data(v8::Handle<v8::Object> val);
                   ^
/root/.node-gyp/0.11.14/src/node_buffer.h:41:19: note:   no known conversion for argument 1 from ‘v8::Persistent<v8::Object>’ to ‘v8::Handle<v8::Object>’
In file included from ../binding.cc:3:0:
../unzipper.h:63:41: error: no matching function for call to ‘Length(v8::Persistent<v8::Object>&)’
       chunkLength = Buffer::Length(chunk);
                                         ^
../unzipper.h:63:41: note: candidates are:
In file included from ../mixer.h:5:0,
                 from ../binding.cc:2:
/root/.node-gyp/0.11.14/src/node_buffer.h:42:20: note: size_t node::Buffer::Length(v8::Handle<v8::Value>)
 NODE_EXTERN size_t Length(v8::Handle<v8::Value> val);
                    ^
/root/.node-gyp/0.11.14/src/node_buffer.h:42:20: note:   no known conversion for argument 1 from ‘v8::Persistent<v8::Object>’ to ‘v8::Handle<v8::Value>’
/root/.node-gyp/0.11.14/src/node_buffer.h:43:20: note: size_t node::Buffer::Length(v8::Handle<v8::Object>)
 NODE_EXTERN size_t Length(v8::Handle<v8::Object> val);
                    ^
/root/.node-gyp/0.11.14/src/node_buffer.h:43:20: note:   no known conversion for argument 1 from ‘v8::Persistent<v8::Object>’ to ‘v8::Handle<v8::Object>’
In file included from ../binding.cc:3:0:
../unzipper.h:65:65: error: ‘malloc’ was not declared in this scope
       channelData = (char**)malloc(unz->channels * sizeof(char*));
                                                                 ^
../unzipper.h:67:58: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::Array>’
         channelData[i] = Buffer::Data(unz->channelBuffers->Get(i)->ToObject());
                                                          ^
../unzipper.h: In destructor ‘virtual pcmutils::Unzipper::UnzipBaton::~UnzipBaton()’:
../unzipper.h:77:16: error: ‘class v8::Persistent<v8::Function>’ has no member named ‘Dispose’
       callback.Dispose();
                ^
../unzipper.h:78:13: error: ‘class v8::Persistent<v8::Object>’ has no member named ‘Dispose’
       chunk.Dispose();
             ^
../unzipper.h:79:23: error: ‘free’ was not declared in this scope
       free(channelData);
                       ^
In file included from ../binding.cc:4:0:
../zipper.h: At global scope:
../zipper.h:17:34: error: expected class-name before ‘{’ token
 class Zipper : public ObjectWrap {
                                  ^
../zipper.h:41:5: error: ‘uv_work_t’ does not name a type
     uv_work_t request;
     ^
../zipper.h:79:34: error: ‘Arguments’ does not name a type
   static Handle<Value> New(const Arguments& args);
                                  ^
../zipper.h:79:45: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   static Handle<Value> New(const Arguments& args);
                                             ^
../zipper.h:80:36: error: ‘Arguments’ does not name a type
   static Handle<Value> Write(const Arguments& args);
                                    ^
../zipper.h:80:47: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   static Handle<Value> Write(const Arguments& args);
                                               ^
../zipper.h:81:70: error: ‘AccessorInfo’ does not name a type
   static Handle<Value> ChannelBuffersGetter(Local<String> str, const AccessorInfo& accessor);
                                                                      ^
../zipper.h:81:84: error: ISO C++ forbids declaration of ‘accessor’ with no type [-fpermissive]
   static Handle<Value> ChannelBuffersGetter(Local<String> str, const AccessorInfo& accessor);
                                                                                    ^
../zipper.h:82:69: error: ‘AccessorInfo’ does not name a type
   static Handle<Value> ChannelsReadyGetter(Local<String> str, const AccessorInfo& accessor);
                                                                     ^
../zipper.h:82:83: error: ISO C++ forbids declaration of ‘accessor’ with no type [-fpermissive]
   static Handle<Value> ChannelsReadyGetter(Local<String> str, const AccessorInfo& accessor);
                                                                                   ^
../zipper.h:83:72: error: ‘AccessorInfo’ does not name a type
   static Handle<Value> SamplesPerBufferGetter(Local<String> str, const AccessorInfo& accessor);
                                                                        ^
../zipper.h:83:86: error: ISO C++ forbids declaration of ‘accessor’ with no type [-fpermissive]
   static Handle<Value> SamplesPerBufferGetter(Local<String> str, const AccessorInfo& accessor);
                                                                                      ^
../zipper.h:84:63: error: ‘AccessorInfo’ does not name a type
   static Handle<Value> ZippingGetter(Local<String> str, const AccessorInfo& accessor);
                                                               ^
../zipper.h:84:77: error: ISO C++ forbids declaration of ‘accessor’ with no type [-fpermissive]
   static Handle<Value> ZippingGetter(Local<String> str, const AccessorInfo& accessor);
                                                                             ^
../zipper.h:87:23: error: ‘uv_work_t’ has not been declared
   static void DoWrite(uv_work_t* req);
                       ^
../zipper.h:88:26: error: ‘uv_work_t’ has not been declared
   static void AfterWrite(uv_work_t* req);
                          ^
../zipper.h:91:21: error: ‘uv_work_t’ has not been declared
   static void DoZip(uv_work_t* req);
                     ^
../zipper.h:92:24: error: ‘uv_work_t’ has not been declared
   static void AfterZip(uv_work_t* req);
                        ^
../zipper.h: In constructor ‘pcmutils::Zipper::Zipper()’:
../zipper.h:22:14: error: class ‘pcmutils::Zipper’ does not have any field named ‘ObjectWrap’
   Zipper() : ObjectWrap(), channels(0), alignment(0), frameAlignment(0), zipping(false), buffer(NULL) {
              ^
../zipper.h:23:20: error: ‘class v8::Persistent<v8::Array>’ has no member named ‘Clear’
     channelBuffers.Clear();
                    ^
../zipper.h:24:19: error: ‘class v8::Persistent<v8::Array>’ has no member named ‘Clear’
     channelsReady.Clear();
                   ^
../zipper.h:25:14: error: ‘class v8::Persistent<v8::Function>’ has no member named ‘Clear’
     callback.Clear();
              ^
../zipper.h: In destructor ‘pcmutils::Zipper::~Zipper()’:
../zipper.h:33:36: error: ‘free’ was not declared in this scope
     if (buffer != NULL) free(buffer);
                                    ^
../zipper.h:35:20: error: ‘class v8::Persistent<v8::Array>’ has no member named ‘Dispose’
     channelBuffers.Dispose();
                    ^
../zipper.h:36:19: error: ‘class v8::Persistent<v8::Array>’ has no member named ‘Dispose’
     channelsReady.Dispose();
                   ^
../zipper.h:37:14: error: ‘class v8::Persistent<v8::Function>’ has no member named ‘Dispose’
     callback.Dispose();
              ^
../zipper.h: In constructor ‘pcmutils::Zipper::Baton::Baton(pcmutils::Zipper*)’:
../zipper.h:45:12: error: ‘class pcmutils::Zipper’ has no member named ‘Ref’
       zip->Ref();
            ^
../zipper.h:46:7: error: ‘request’ was not declared in this scope
       request.data = this;
       ^
../zipper.h: In destructor ‘virtual pcmutils::Zipper::Baton::~Baton()’:
../zipper.h:49:12: error: ‘class pcmutils::Zipper’ has no member named ‘Unref’
       zip->Unref();
            ^
../zipper.h: In constructor ‘pcmutils::Zipper::WriteBaton::WriteBaton(pcmutils::Zipper*, v8::Handle<v8::Function>, int)’:
../zipper.h:58:47: error: no matching function for call to ‘v8::Persistent<v8::Function>::New(v8::Handle<v8::Function>&)’
       callback = Persistent<Function>::New(cb_);
                                               ^
../zipper.h:58:47: note: candidate is:
In file included from /root/.node-gyp/0.11.14/src/node.h:61:0,
                 from ../binding.cc:1:
/root/.node-gyp/0.11.14/deps/v8/include/v8.h:5724:4: note: static T* v8::PersistentBase<T>::New(v8::Isolate*, T*) [with T = v8::Function]
 T* PersistentBase<T>::New(Isolate* isolate, T* that) {
    ^
/root/.node-gyp/0.11.14/deps/v8/include/v8.h:5724:4: note:   candidate expects 2 arguments, 1 provided
In file included from ../binding.cc:4:0:
../zipper.h: In destructor ‘virtual pcmutils::Zipper::WriteBaton::~WriteBaton()’:
../zipper.h:61:16: error: ‘class v8::Persistent<v8::Function>’ has no member named ‘Dispose’
       callback.Dispose();
                ^
../zipper.h: In constructor ‘pcmutils::Zipper::ZipBaton::ZipBaton(pcmutils::Zipper*)’:
../zipper.h:69:65: error: ‘malloc’ was not declared in this scope
       channelData = (char**)malloc(zip->channels * sizeof(char*));
                                                                 ^
../zipper.h:71:58: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::Array>’
         channelData[i] = Buffer::Data(zip->channelBuffers->Get(i)->ToObject());
                                                          ^
../zipper.h: In destructor ‘virtual pcmutils::Zipper::ZipBaton::~ZipBaton()’:
../zipper.h:75:23: error: ‘free’ was not declared in this scope
       free(channelData);
                       ^
In file included from ../binding.cc:5:0:
../formatter.h: At global scope:
../formatter.h:17:37: error: expected class-name before ‘{’ token
 class Formatter : public ObjectWrap {
                                     ^
../formatter.h:37:5: error: ‘uv_work_t’ does not name a type
     uv_work_t request;
     ^
../formatter.h:71:34: error: ‘Arguments’ does not name a type
   static Handle<Value> New(const Arguments& args);
                                  ^
../formatter.h:71:45: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   static Handle<Value> New(const Arguments& args);
                                             ^
../formatter.h:72:37: error: ‘Arguments’ does not name a type
   static Handle<Value> Format(const Arguments& args);
                                     ^
../formatter.h:72:48: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   static Handle<Value> Format(const Arguments& args);
                                                ^
../formatter.h:75:24: error: ‘uv_work_t’ has not been declared
   static void DoFormat(uv_work_t* req);
                        ^
../formatter.h:76:27: error: ‘uv_work_t’ has not been declared
   static void AfterFormat(uv_work_t* req);
                           ^
../formatter.h: In constructor ‘pcmutils::Formatter::Formatter()’:
../formatter.h:22:17: error: class ‘pcmutils::Formatter’ does not have any field named ‘ObjectWrap’
   Formatter() : ObjectWrap(), inFormat(0), outFormat(0),
                 ^
../formatter.h: In destructor ‘pcmutils::Formatter::~Formatter()’:
../formatter.h:32:36: error: ‘free’ was not declared in this scope
     if (buffer != NULL) free(buffer);
                                    ^
../formatter.h: In constructor ‘pcmutils::Formatter::Baton::Baton(pcmutils::Formatter*)’:
../formatter.h:41:12: error: ‘class pcmutils::Formatter’ has no member named ‘Ref’
       fmt->Ref();
            ^
../formatter.h:42:7: error: ‘request’ was not declared in this scope
       request.data = this;
       ^
../formatter.h: In destructor ‘virtual pcmutils::Formatter::Baton::~Baton()’:
../formatter.h:45:12: error: ‘class pcmutils::Formatter’ has no member named ‘Unref’
       fmt->Unref();
            ^
../formatter.h: In constructor ‘pcmutils::Formatter::FormatBaton::FormatBaton(pcmutils::Formatter*, v8::Handle<v8::Function>, v8::Handle<v8::Object>)’:
../formatter.h:60:47: error: no matching function for call to ‘v8::Persistent<v8::Function>::New(v8::Handle<v8::Function>&)’
       callback = Persistent<Function>::New(cb_);
                                               ^
../formatter.h:60:47: note: candidate is:
In file included from /root/.node-gyp/0.11.14/src/node.h:61:0,
                 from ../binding.cc:1:
/root/.node-gyp/0.11.14/deps/v8/include/v8.h:5724:4: note: static T* v8::PersistentBase<T>::New(v8::Isolate*, T*) [with T = v8::Function]
 T* PersistentBase<T>::New(Isolate* isolate, T* that) {
    ^
/root/.node-gyp/0.11.14/deps/v8/include/v8.h:5724:4: note:   candidate expects 2 arguments, 1 provided
In file included from ../binding.cc:5:0:
../formatter.h:61:45: error: no matching function for call to ‘v8::Persistent<v8::Object>::New(v8::Handle<v8::Object>&)’
       chunk = Persistent<Object>::New(chunk_);
                                             ^
../formatter.h:61:45: note: candidate is:
In file included from /root/.node-gyp/0.11.14/src/node.h:61:0,
                 from ../binding.cc:1:
/root/.node-gyp/0.11.14/deps/v8/include/v8.h:5724:4: note: static T* v8::PersistentBase<T>::New(v8::Isolate*, T*) [with T = v8::Object]
 T* PersistentBase<T>::New(Isolate* isolate, T* that) {
    ^
/root/.node-gyp/0.11.14/deps/v8/include/v8.h:5724:4: note:   candidate expects 2 arguments, 1 provided
In file included from ../binding.cc:5:0:
../formatter.h:62:37: error: no matching function for call to ‘Data(v8::Persistent<v8::Object>&)’
       chunkData = Buffer::Data(chunk);
                                     ^
../formatter.h:62:37: note: candidates are:
In file included from ../mixer.h:5:0,
                 from ../binding.cc:2:
/root/.node-gyp/0.11.14/src/node_buffer.h:40:19: note: char* node::Buffer::Data(v8::Handle<v8::Value>)
 NODE_EXTERN char* Data(v8::Handle<v8::Value> val);
                   ^
/root/.node-gyp/0.11.14/src/node_buffer.h:40:19: note:   no known conversion for argument 1 from ‘v8::Persistent<v8::Object>’ to ‘v8::Handle<v8::Value>’
/root/.node-gyp/0.11.14/src/node_buffer.h:41:19: note: char* node::Buffer::Data(v8::Handle<v8::Object>)
 NODE_EXTERN char* Data(v8::Handle<v8::Object> val);
                   ^
/root/.node-gyp/0.11.14/src/node_buffer.h:41:19: note:   no known conversion for argument 1 from ‘v8::Persistent<v8::Object>’ to ‘v8::Handle<v8::Object>’
In file included from ../binding.cc:5:0:
../formatter.h:63:41: error: no matching function for call to ‘Length(v8::Persistent<v8::Object>&)’
       chunkLength = Buffer::Length(chunk);
                                         ^
../formatter.h:63:41: note: candidates are:
In file included from ../mixer.h:5:0,
                 from ../binding.cc:2:
/root/.node-gyp/0.11.14/src/node_buffer.h:42:20: note: size_t node::Buffer::Length(v8::Handle<v8::Value>)
 NODE_EXTERN size_t Length(v8::Handle<v8::Value> val);
                    ^
/root/.node-gyp/0.11.14/src/node_buffer.h:42:20: note:   no known conversion for argument 1 from ‘v8::Persistent<v8::Object>’ to ‘v8::Handle<v8::Value>’
/root/.node-gyp/0.11.14/src/node_buffer.h:43:20: note: size_t node::Buffer::Length(v8::Handle<v8::Object>)
 NODE_EXTERN size_t Length(v8::Handle<v8::Object> val);
                    ^
/root/.node-gyp/0.11.14/src/node_buffer.h:43:20: note:   no known conversion for argument 1 from ‘v8::Persistent<v8::Object>’ to ‘v8::Handle<v8::Object>’
In file included from ../binding.cc:5:0:
../formatter.h: In destructor ‘virtual pcmutils::Formatter::FormatBaton::~FormatBaton()’:
../formatter.h:66:16: error: ‘class v8::Persistent<v8::Function>’ has no member named ‘Dispose’
       callback.Dispose();
                ^
../formatter.h:67:13: error: ‘class v8::Persistent<v8::Object>’ has no member named ‘Dispose’
       chunk.Dispose();
             ^
make: *** [Release/obj.target/binding/binding.o] Error 1
make: Leaving directory `/tmp/node_modules/pcm-utils/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/node/node-v0.11.14/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1059:12)
gyp ERR! System Linux 3.13.0-37-generic
gyp ERR! command "node" "/usr/local/node/node-v0.11.14/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/node_modules/pcm-utils
gyp ERR! node -v v0.11.14
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

npm ERR! Linux 3.13.0-37-generic
npm ERR! argv "/usr/local/node/node-v0.11.14/bin/node" "/usr/local/node/node-default/bin/npm" "install" "pcm-utils"
npm ERR! node v0.11.14
npm ERR! npm  v2.0.0
npm ERR! code ELIFECYCLE
npm ERR! pcm-utils@0.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pcm-utils@0.0.2 install script.
npm ERR! This is most likely a problem with the pcm-utils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pcm-utils
npm ERR! There is likely additional logging output above.
root@node-1:/tmp:
```

I will try to find a workaround later

**Comment by xdissent** [comment]
Ok _this_ one is easy - there's no node 0.11 support whatsoever yet. The c++ api changes between 0.10 and 0.11 are massive. We'll probably just wait until some time after 0.12 lands officially (very soon) since not many people will be running 0.11/0.12 for quite some time. Thanks for the report though!
